### ISSUE TITLE
error in parsing detailed.json

### ISSUE THREAD

**Issue by benyblack** [soheilpro/mon#34]
when i try to use detailed.json i see this:

$ mon detailed.json
undefined:2
    groups: [{
    ^
SyntaxError: Unexpected token g
    at Object.parse (native)
    at Function.Config.parse (c:\Users\behnam\AppData\Roaming\npm\node_modules\monjs\config.js:7:21)
    at Object.<anonymous> (c:\Users\behnam\AppData\Roaming\npm\node_modules\monjs\mon.js:64:25)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

it seems to must be like this "groups": ...

**Comment by benyblack** [comment]
oh my fault!
copy paste issue
